name: ⚠️ Release
on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - minor
          - patch
          - major
  schedule:
    - cron: '0 7 * * 1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - uses: taiga-family/ci/actions/run/release-it@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
