name: ⚠️ Release
on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - minor
          - patch
          - major
  schedule:
    - cron: '0 7 * * 1'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: taiga-family/actions/release-it@399268333d80c132c3bf9939f33e4db8b7f11be5 # v2.11.0
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
