name: 🤖 Run renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Override default log level'
        required: false
        type: choice
        options:
          - debug
          - info
  schedule:
    - cron: '0 */1 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_CONFIG_FILE: default.json
      LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
      RENOVATE_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      RENOVATE_ALLOWED_COMMANDS: '.*'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-variables@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - uses: taiga-family/actions/setup-node@5b954545ec33833478961976b2ce4fd3c6b89149 # v2.7.0
      - run: |
          npx renovate \
                --autodiscover=true \
                --autodiscover-filter='taiga-family/*' \
                --allowed-post-upgrade-commands='.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
