name: 🤖 Run renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Override default log level'
        required: false
        type: choice
        options:
          - debug
          - info
  schedule:
    - cron: '0 */1 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_CONFIG_FILE: default.json
      LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
      RENOVATE_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
      RENOVATE_ALLOWED_COMMANDS: '.*'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/actions/setup-variables@a6230c2ffdf53253580ec058dd4faccdb01ac85a # v2.4.0
      - uses: taiga-family/actions/setup-node@a6230c2ffdf53253580ec058dd4faccdb01ac85a # v2.4.0
      - run: |
          npx renovate \
                --autodiscover=true \
                --autodiscover-filter='taiga-family/*' \
                --allowed-post-upgrade-commands='.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
