name: 🤖 Run renovate
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Override default log level'
        required: false
        type: choice
        options:
          - debug
          - info
  schedule:
    - cron: '0 */1 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_CONFIG_FILE: default.json
      LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
      RENOVATE_TOKEN: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: taiga-family/ci/actions/setup/variables@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
      - uses: taiga-family/ci/actions/setup/node@c5bcf64b54eb51e9274fa667e69cfd0d2f37adfd # v1.209.0
      - run: |
          npx renovate \
                --autodiscover=true \
                --autodiscover-filter='taiga-family/*' \
                --allowed-post-upgrade-commands='.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
